deployment:
  tasks:
    - export DEPLOYPATH=/home3/apren173/api.anuncielo.com/
    
    - /bin/cp -R app bootstrap config database public resources routes storage artisan composer.json composer.lock package.json vite.config.js $DEPLOYPATH

    - cd $DEPLOYPATH
    
    # Limpiar y optimizar Laravel
    - echo "Running Laravel optimizations..." >> deployment.log
    - php artisan config:clear >> deployment.log 2>&1
    - php artisan cache:clear >> deployment.log 2>&1
    - php artisan route:cache >> deployment.log 2>&1
    - php artisan config:cache >> deployment.log 2>&1
    - php artisan view:cache >> deployment.log 2>&1

    # Finalizar despliegue
    - echo "Deployment completed at $(date)" >> deployment.log
    - echo "---------------------------------------------" >> deployment.log

    